version: '3'

services:
  mongo:
    restart: unless-stopped
    image: mongo:4.0
    container_name: mongo
    expose:
      - 27017
    networks:
      - rrnet
  
  roborally:
    restart: unless-stopped
    image: ben-morin/roborally
    container_name: roborally
    ports:
        - 3000:3000
    depends_on:
        - mongo
    environment:
        - MONGO_URL=mongodb://mongo:27017/roborally
        - ROOT_URL=http://localhost:3000
    networks:
        - rrnet
    
networks:
  rrnet:
    driver: bridge
