########################
### Dev container
########################

FROM node:24 AS build

# allows meteor to build in docker VM with 2GB runtime memory
# ENV TOOL_NODE_FLAGS "--max-old-space-size=1920 --optimize_for_size --gc-interval=100"

ENV METEOR_ALLOW_SUPERUSER=1
ENV BROWSERSLIST_IGNORE_OLD_DATA=1

ENV CXXFLAGS=-std=gnu++17
RUN curl https://install.meteor.com/\?release\=3.5 | sh

WORKDIR /usr/app

COPY package.json package-lock.json ./
RUN meteor npm ci || meteor npm install

ENV PORT=3000
EXPOSE $PORT

# Rspack dev server (@meteorjs/rspack defaults to 8080)
EXPOSE 8080

ENTRYPOINT ["/usr/app/entrypoint.sh"]
CMD [ "meteor", "run" ]

