// Type declarations for the Atmosphere packages the app imports — written by hand rather
// than generated by zodern:types. Two of the three ship a .d.ts of their own and neither
// fits: jam:easy-schema's exports no `AnyOf`; jam:method's infers `run`'s argument from
// `schema:`, which these methods deliberately never pass (see both/schemas/methods.ts); and
// both import types from `zod`, `simpl-schema` and `meteor/npm-mongo`, none of which the
// app has. The generated file would also live under .meteor/local, which ci.yml — no
// Meteor toolchain — cannot have. So this declares exactly the surface the app uses: a new
// import from one of these packages is a compile error until it is written down here.
//
// No top-level import or export in this file. That would make it a module, and every
// `declare module` below would become an augmentation of a module that has to exist first.

declare module 'meteor/jam:easy-schema' {
  import type { Match } from 'meteor/check';

  // `Pattern[]` rather than `[Pattern]`: a schema written as `[String]` is inferred as
  // `StringConstructor[]`, not a tuple.
  export type Pattern =
    | StringConstructor
    | NumberConstructor
    | BooleanConstructor
    | DateConstructor
    | ObjectConstructor
    | Match.Matcher<unknown>
    | Pattern[]
    | { [key: string]: Pattern };

  // The document a schema describes. Every key is present in this type; `Doc` in
  // both/schemas/infer.ts is what makes the undefined-able ones optional.
  export type Infer<T> = T extends StringConstructor
    ? string
    : T extends NumberConstructor
      ? number
      : T extends BooleanConstructor
        ? boolean
        : T extends DateConstructor
          ? Date
          : T extends ObjectConstructor
            ? Record<string, unknown>
            : T extends Match.Matcher<infer U>
              ? U
              : T extends (infer E)[]
                ? Infer<E>[]
                : T extends { [key: string]: Pattern }
                  ? { [K in keyof T]: Infer<T[K]> }
                  : never;

  export const ID: Match.Matcher<string>;
  // `unknown`, not `any`: the one field that uses it is cast where it is read.
  export const Any: Match.Matcher<unknown>;
  /** The key may be absent. */
  export function Optional<T extends Pattern>(pattern: T): Match.Matcher<Infer<T> | undefined>;
  /** The key is present and its value matches one of the patterns. */
  export function AnyOf<T extends Pattern[]>(...patterns: T): Match.Matcher<Infer<T[number]>>;
  export function check<T extends Pattern>(data: unknown, schema: T): asserts data is Infer<T>;
  export const EasySchema: {
    configure(options: {
      validationLevel?: 'strict' | 'moderate' | 'off';
      additionalBsonTypes?: Record<string, string>;
      autoCheck?: boolean;
      autoAttachJSONSchema?: boolean;
    }): void;
  };
}

declare module 'meteor/jam:method' {
  interface MethodOptions {
    name: string;
    rateLimit?: { limit: number; interval: number };
    open?: boolean;
    serverOnly?: boolean;
  }
  // One argument object. `A` is taken from `run`'s annotated parameter; leave the
  // annotation off and `A` is `unknown`, which is exactly the error wanted.
  export function createMethod<A, R>(
    definition: MethodOptions & {
      validate: (args: A) => void;
      run: (this: Meteor.MethodThisType, args: A) => Promise<R> | R;
    }
  ): (args: A) => Promise<R>;
  // No argument at all (`isEmailAvailable`).
  export function createMethod<R>(
    definition: MethodOptions & { run: (this: Meteor.MethodThisType) => Promise<R> | R }
  ): () => Promise<R>;
  export const Methods: {
    configure(options: { serverOnly?: boolean; open?: boolean; loggedOutError?: Error }): void;
  };
}

declare module 'meteor/quave:synced-cron' {
  export const SyncedCron: {
    config(options: { log?: boolean }): void;
    add(job: {
      name: string;
      schedule: (parser: { text(spec: string): unknown }) => unknown;
      // The package awaits the return value and then discards it unless the job is
      // `persist`ed, which none here is — so a job may resolve to anything. `Recover
      // stalled turns` resolves to the array of replay promises it deliberately does not
      // wait for; see server/resume.ts.
      job: () => unknown;
    }): void;
    start(): void;
  };
}

// The `schema` option jam:easy-schema adds to the constructor, with the two type arguments
// the collections give explicitly — the document type and the transform's type — so that
// `findOneAsync` hands back a `Game`, not a bare document.
declare module 'meteor/mongo' {
  import type { Document } from 'mongodb';
  namespace Mongo {
    interface CollectionStatic {
      new <T extends Document, U = T>(
        name: string,
        options: {
          schema: import('meteor/jam:easy-schema').Pattern;
          transform?: (doc: T) => U;
        }
      ): Collection<T, U>;
    }
  }
}
